library(tidyverse)
library(knitr)

# Github link:
# https://github.com/stat301-2-2024-winter/final-project-2-celenakim

allies_codebook_tibble <- tibble(
  Variables = c("comment_id",
                "username",
                "comment",
                "likes",
                "replies",
                "parent_comment_id" ),
  Meaning = c("the title of the movie", 
              "the year the movie was released",
              "the script type classification of the movie", 
              "the movie's Rotten Tomatoes score, based on ratings from professional critics",
              "the movie's Metacritic score, based on the weighted average of ratings given by critics", 
              "the average of the movie's Rotten Tomatoes critic score and Metacritic critic score",
              "the movie's Rotten Tomatoes score, based on ratings from the general audience", 
              "the movie's Metacritic score, based on the average of ratings submitted by Metacritic users",
              "the movie's Rotten Tomatoes audience score minus the Metacritic audience score", 
              "the average of the movie's Rotten Tomatoes audience score and Metacritic audience score",
              "the movie's average critics rating minus the average audience rating", 
              "the main genre of the movie",
              "the multiple genres the movie may fall into", 
              "how much revenue the movie made during its opening weekend",
              "how much revenue the movie made during its opening weekend (in millions)", 
              "the movie's total box office revenue, generated within the US",
              "the movie's total box office revenue, generated within the US (in millions)", 
              "the total box office revenue generated by the movie from international markets outside the US (in millions)",
              "the total box office revenue generated by the movie from international markets outside the US", 
              "the total box office revenue generated by the movie from screenings worldwide, including both its domestic and foreign earnings",
              "the total box office revenue generated by the movie from screenings worldwide, including both its domestic and foreign earnings (in millions)", 
              "the percent that the movie's foreign gross makes up its worldwide gross",
              "the total cost of the movie's product (in millions)", 
              "the percent of the movie's budget that was earned back in total after its production",
              "the percent of the movie's budget that was earned back during opening weekend alone", 
              "whether or not the movie earned an Oscar award",
              "the type of Oscar the movie earned, if applicable", 
              "the company responsible for marketing and releasing the movie (only available for 2019-2022 movies)",
              "the movie's IMDb score, on a scale of 1 to 10 (only available for 2019-2022 movies)", 
              "the movie's IMDb score minus its Rotten Tomatoes score (only available for 2019-2022 movies)",
              "the date that the movie was released in the US",
              "the season that the movie was released in")
)

write_csv(codebook_tibble, "data/movie_data_codebook.csv")